# 系统配置
log_dir: "logs"          # 日志目录
data_dir: "data"         # 数据目录
log_level: "INFO"        # 日志级别

# 账户配置
account:
  account_id: "40126980"         # 资金账号
  account_type: "STOCK"  # 账户类型：STOCK-股票，FUTURE-期货
  token: ""              # API令牌（如需要）

# 交易配置
trading:
  order_timeout: 60      # 订单超时时间（秒）
  max_positions: 5       # 最大持仓数
  risk_limit: 0.1        # 风险限额（占总资金比例）
  trading_hours:         # 交易时段
    - ["09:30", "11:30"]
    - ["13:00", "15:00"]

# 回测配置
backtest:
  start_date: "2023-01-01"  # 回测起始日期
  end_date: "2023-12-31"    # 回测结束日期
  initial_capital: 1000000   # 初始资金
  commission_rate: 0.0003    # 手续费率
  slippage: 0.0001          # 滑点率