# 系统配置
log_dir: "logs"          # 日志目录
data_dir: "data"         # 数据目录
log_level: "INFO"        # 日志级别

# 账户配置
account:
  account_id: "40126980"         # 资金账号
  account_type: "STOCK"  # 账户类型：STOCK-股票，FUTURE-期货
  token: ""              # API令牌（如需要）

# 交易配置
trading:
  order_timeout: 60      # 订单超时时间（秒）
  max_positions: 5       # 最大持仓数
  risk_limit: 0.1        # 风险限额（占总资金比例）
  trading_hours:         # 交易时段
    - ["09:30", "11:30"]
    - ["13:00", "15:00"]

# 回测配置
backtest:
  start_date: "2023-01-01"  # 回测起始日期
  end_date: "2023-12-31"    # 回测结束日期
  initial_capital: 1000000   # 初始资金
  commission_rate: 0.0003    # 手续费率
  slippage: 0.0001          # 滑点率

# 数据配置
data:
  universe: [              # 交易标的池 - A股主板股票池（示例）
    "600000.SH",          # 浦发银行
    "600036.SH",          # 招商银行
    "601318.SH",          # 中国平安
    "600519.SH",          # 贵州茅台
    "600276.SH",          # 恒瑞医药
    "600887.SH",          # 伊利股份
    "601166.SH",          # 兴业银行
    "600030.SH",          # 中信证券
    "600031.SH",          # 三一重工
    "600009.SH"           # 上海机场
  ]
  history_length: 100      # 加载的历史数据长度（交易日）
  indicators: [            # 需要计算的技术指标
    "MA",                  # 移动平均
    "RSI",                 # 相对强弱指数
    "MACD",                # 平滑异同移动平均
    "VOLUME"               # 成交量指标
  ]

# 首板打板策略参数
strategy_params:
  limit_up_pct: 0.097       # 涨停判断阈值，略小于10%以避免误差
  volume_ratio: 2.0         # 成交量放大倍数要求
  turnover_rate: 5.0        # 换手率最小要求
  max_boards: 1             # 最大连板数，首板为1
  stop_loss_pct: 0.03       # 止损比例
  stop_profit_pct: 0.05     # 止盈比例
  max_position_pct: 0.2     # 单只股票最大仓位